### PR TITLE
Revamp Crystinium texture

### LINKED ISSUE #86: Enhancement: Animate or remove floating pixels on Crystinium texture
The Crystinium flower has pale floating pixels in its texture that aren't connected to the flower. I presume that these are intended to be some sort of glimmering particles, like the ones that fall in the Quartz Canyon biome. If this is the case, I would suggest to either make this more clear by giving Crystiniums an animated texture with these particles slowly drifting down, or remove them from the texture, and instead give Crystiniums the ability to create particles, specifically the ones that fall in the Quartz Canyon biome.~
Currently, the floating pixels in the texture look strange and unclear as to what they are supposed to be.

Edit: I just realised that Crystiniums do actually emit the very particles I suggested, just not very noticeably.~ Still, my concerns about the floating pixels stand.

### PR DESCRIPTION
**Pull request by saltyseadoggo**
I saw that #86 was given the "Good first issue" label, which I took to mean that you wouldn't mind if someone were to take a shot at fixing it, so I did. I removed the floating pixels, as having any sort of animated particles on the texture when the Crystinium already emits particles seems redundant, and I also revamped it a bit, improving the shape of its stems, and reducing the number of yellow shades from eleven down to just four to comply with the limited palettes Jappa textures use. I sincerely hope you like it.~

Left is the current texture, right is mine.~
crystiniums comparison

Edit: I have revamped the item textures as well to match the block texture, and to have floaters representing the particles. Left is the current texture, right is mine.~
crystinium item comparison

### CODE REVIEW

**Comment by NeusFear** [comment]
If you wouldn't mind posting a picture here in your PR so we can easily compare new to old. Just a side by side comparison always makes it simpler for reviewers

**Comment by saltyseadoggo** [comment]
Of course. Would you like them scaled up for purposes of viewing, or at their original resolution?

**Comment by NeusFear** [comment]
Scaled up would be great!

**Comment by ghost** [comment]
I like the idea of removing the little particles in the actual block texture, but it might be good to keep them in the item texture. This might require copying the texture and modifying the item model

**Comment by saltyseadoggo** [comment]
I've added a comparison photo.~
The Crystinium actually already uses its own item texture. I could revamp it as I have with the block texture, and have some floaters in its texture as you have suggested.~

**Comment by saltyseadoggo** [comment]
I have revamped the item textures as well, as per Vaerian's request. Comparison images are in the original post.~

**Comment by ghost** [comment]
LGTM What do you think @NeusFear

**Comment by NeusFear** [comment]
It seems weird to me that the branches of the block and item are different. I'd prefer they were the same shape.

**Comment by saltyseadoggo** [comment]
For the record, that's how you two had them originally :shrug: I can totally make them match, though.~

**Comment by NeusFear** [comment]
That's awkward. Yes, may as well while we're at it eh?
Thanks!

**Comment by saltyseadoggo** [comment]
I have updated the item texture, as well as the comparison images above.~

**Pull request merged**
