### PR TITLE
Initial port to 1.16.2

### PR DESCRIPTION
**Pull request by shartte**
This depends on a local preview-build of the ported biome api, as well as a relatively half-assed port of the underlying lib (that does not even affect the features used by cinderscapes, rather the other mixins it contains).
See here: https://github.com/TerraformersMC/Terraform/pull/19

The local preview-build is using this PR: https://github.com/FabricMC/fabric/pull/1053

This certainly needs more testing since I never saw Cinderscapes in 1.16.1 and have no point of reference.

Feel free to hit me up on Fabricord if you want to discuss the details of this, next steps and how a painless migration to JSON biomes could look like in 1.17.

Marked as draft not because it does not work, but because it depends on the unmerged fabric-api and needs some general code cleanup.

### CODE REVIEW

**Comment by shartte** [comment]
grafik
grafik
grafik
grafik
grafik

**Comment by ghost** [comment]
@shartte I made some changes, removed Terraform, everything *should* launch now, but I think I'm having trouble with the actual new biomes api. It would awesome if you could pull my changes and try to run them and troubleshoot what might be happening.

**Comment by shartte** [comment]
Aight will do

**Comment by shartte** [comment]
@Vaerian Fixed it. The static-constructor of CinderscapesBiomes was never invoked because nothing during startup was referencing it anymore. I've added a dummy init() method and just call it during init at the appropriate time, which forces it to run, registering the biomes.

I also updated to the latest version of the biome API PR since that is probably going to be merged into fabric-api soon (just a package/name/version-change. no functional changes). You'll probably need to git pull and run gradlew publishToMavenLocal again for the PR though.

**Comment by ghost** [comment]
Awesome thanks, can't believe it was that dumb of a mistake

**Comment by ghost** [comment]
This is for me lol

- [ ] Make sure to port this to whatever https://github.com/TerraformersMC/Terraform/blob/1.16/src/main/java/com/terraformersmc/terraform/mixin/MixinBlockEntityType.java

**Comment by ghost** [comment]
I'm just going to go ahead and pull this into a branch in our repo so you don't have to keep holding onto your fork. Plus it's nearly done except for figuring out Terraform and I don't know when that's going to happen. Thank you again for all your help, this wouldn't have been able to get done without you.

**Pull request merged**
